[package]
name = "rmail_common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
anyhow = "1.0"
argon2 = "0.4"
password-hash = "0.4"
rand = "0.8"
serde_json = "1.0"
rusqlite = { version = "0.29", features = ["bundled"] }

# SCRAM helpers
pbkdf2 = "0.11"
hmac = "0.12"
sha2 = "0.10"
base64 = "0.21"
unicode-normalization = "0.1"
